// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const  web = FirebaseOptions(
    apiKey: 'AIzaSyCTjiFYZbVLkV2QKWMJTCLX5DH-dxFEskQ',
    appId: '1:567189349177:web:69eea7ce3265f048d4bee8',
    messagingSenderId: '567189349177',
    projectId: 'trainxapp-a1ad0',
    authDomain: 'trainxapp-a1ad0.firebaseapp.com',
    storageBucket: 'trainxapp-a1ad0.firebasestorage.app',
    measurementId: 'G-MJRLP09SHH',
  );

  static const  android = FirebaseOptions(
    apiKey: 'AIzaSyBws9bTATHVe4OEMAmcCDyKK1aaMMuhzrc',
    appId: '1:567189349177:android:7aa56814c2eb1042d4bee8',
    messagingSenderId: '567189349177',
    projectId: 'trainxapp-a1ad0',
    storageBucket: 'trainxapp-a1ad0.firebasestorage.app',
  );

  static const  ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRqdLEUY1uyAn10T0XiaMlBaJBgv6I3c',
    appId: '1:567189349177:ios:7d047092bb9b5e3ad4bee8',
    messagingSenderId: '567189349177',
    projectId: 'trainxapp-a1ad0',
    storageBucket: 'trainxapp-a1ad0.firebasestorage.app',
    iosBundleId: 'com.example.trainxApp',
  );
}
